### ISSUE TITLE
add sample controllers, models, services, utils and validations

### ISSUE THREAD

**Issue by lavendar-k** [angelsoft-team/backend-express-mongoose-boilerplate#4]

**Comment by stuartyng** [comment]
add all stuffs related with user and role.

**Comment by lavendar-k** [comment]
import {
  Avatar, Contact, FolderId, GoogleCredential,
} from './models';

class AppUser {
  public id: string;

  public name: string;

  public username: string;

  public avatar: Avatar;

  public contact: Contact;

  public setting: object;

  public bookmarks: string[];

  public subscriptions: string[];

  public widgetBookmarks: string[];

  public defaultUserFolder: string;

  public defaultAssetFolder: string;

  public folders: string[];

  public folderIds: FolderId[];

  public linkedIds: string[];

  public creatorAssetIds: string[];

  public channelIds: string[];

  public favorites: string[];

  public zipCodes: string[];

  public access: string[];

  public keywords: string[];

  public categories: string[];

  public timestamp: number;

  public updatedAt: number;

  public role: string;

  public domain: string;

  public locationId: string;

  public googleCredential: GoogleCredential;

  public loginAt: number;

  public loginCount: number;

  public activated: boolean;

  public data: object;

  constructor(
    id: string,
    name: string,
    username: string,
    avatar: Avatar,
    contact: Contact,
    setting: object,
    bookmarks: string [],
    subscriptions: string [],
    widgetBookmarks: string[],
    defaultUserFolder: string,
    defaultAssetFolder: string,
    folders: string [],
    folderIds: FolderId[],
    linkedIds: string[],
    creatorAssetIds: string[],
    channelIds: string[],
    favorites: string[],
    zipCodes: string[],
    access: string[],
    keywords: string[],
    categories: string[],
    role: string,
    domain: string,
    locationId: string,
    googleCredential: GoogleCredential,
    loginAt: number,
    loginCount: number,
    data: object,
  ) {
    this.id = id;
    this.name = name;
    this.username = username;
    this.avatar = avatar;
    this.contact = contact;
    this.setting = setting;
    this.bookmarks = bookmarks;
    this.subscriptions = subscriptions;
    this.widgetBookmarks = widgetBookmarks;
    this.defaultUserFolder = defaultUserFolder;
    this.defaultAssetFolder = defaultAssetFolder;
    this.folders = folders;
    this.folderIds = folderIds;
    this.linkedIds = linkedIds;
    this.creatorAssetIds = creatorAssetIds;
    this.channelIds = channelIds;
    this.favorites = favorites;
    this.zipCodes = zipCodes;
    this.access = access;
    this.keywords = keywords;
    this.categories = categories;
    this.timestamp = new Date().valueOf();
    this.updatedAt = new Date().valueOf();
    this.role = role;
    this.domain = domain;
    this.locationId = locationId;
    this.googleCredential = googleCredential;
    this.loginAt = loginAt;
    this.loginCount = loginCount;
    this.activated = false;
    this.data = data;
  }
}

export default AppUser;
